### ISSUE TITLE
elastic4s 2.0 release

### ISSUE THREAD

**Issue by sksamuel** [sksamuel/elastic4s#389]
- [x] Bump to 2.0 / fix code / remove deprecations #400
- [x] Merge filters and queries #390  
- [x] Consider deprecating the dot free syntax #394 
- [x] Consider rich responses for requests #396
- [x] Scalatest matchers for testkit #399
- [x] #392 Improve publish actor
- [x] #376 Any plan for supporting termvector api? 
- [x] #465 Similarity issues
- [x] Clean up the index/type implicits #398
- [x] #391 Rework client class to expose node
- [x] #401 Scroll id in publisher bug
- [x] Make definitions serializable #402
- [x] Improve tokenizers/tokenfilters/analyzers #404
- [x] Mapping should detect fields with same name but diff types #410
- [x] Dynamic templates don't support mapping without field name #451
- [x] DSL cannot produce mappings for indexing the _id field #462
- [x] No way to get a list of all index names using elastic4s #407
